version: '2.2'
services:
  cassandra1:
    container_name: cassandra_1
    # command: --init-file /creation_base.cql
    image: cassandra
    ports:
      - '9042:9042'
      - '9160:9160'
    environment:
      - CASSANDRA_SEEDS=cassandra_1,cassandra_2
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=password123
    volumes:
      - ./db-data/1:/var/lib/cassandra
      #- ./init.cql:/init.cql
      - ./ressources:/ressources


  cassandra2:
    container_name: cassandra_2
    image: cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra_1,cassandra_2
      - CASSANDRA_PASSWORD=password123
    volumes:
      - ./db-data/2:/var/lib/cassandra

  fastAPI:
    container_name: fastAPI
    build : .
    image: fastapi
    ports:
      - '8000:8000'
